// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH78xqEOc-i8RvbbpAHgW_Nx8lhL5i69A',
    appId: '1:440252030864:web:b6462cf0e642814601dd15',
    messagingSenderId: '440252030864',
    projectId: 'restaurant-booking-c7005',
    authDomain: 'restaurant-booking-c7005.firebaseapp.com',
    storageBucket: 'restaurant-booking-c7005.firebasestorage.app',
    measurementId: 'G-D2X7MHCJH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjR3U_jBBccMmf7f32xhF0GBAj6LlS7Tk',
    appId: '1:440252030864:android:62dcd2a0b8db955401dd15',
    messagingSenderId: '440252030864',
    projectId: 'restaurant-booking-c7005',
    storageBucket: 'restaurant-booking-c7005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoPaTwlk7bkzESNfZUpCHVkhRd6DZKbEs',
    appId: '1:440252030864:ios:b1d6f944df22855101dd15',
    messagingSenderId: '440252030864',
    projectId: 'restaurant-booking-c7005',
    storageBucket: 'restaurant-booking-c7005.firebasestorage.app',
    iosBundleId: 'com.example.restaurantBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH78xqEOc-i8RvbbpAHgW_Nx8lhL5i69A',
    appId: '1:440252030864:web:947d50c082de52de01dd15',
    messagingSenderId: '440252030864',
    projectId: 'restaurant-booking-c7005',
    authDomain: 'restaurant-booking-c7005.firebaseapp.com',
    storageBucket: 'restaurant-booking-c7005.firebasestorage.app',
    measurementId: 'G-NFBMC3PCK3',
  );
}
